# Tomcat Server
server:
  port: 8888
  undertow:
    max-http-post-size: 1KB
    accesslog:
      enabled: false


  #HTTP Response Compression
  compression:
    enabled: false
    min-response-size: 10KB
    mime-types: application/json


# Logging
logging:
  level:
    web: info
    sql: info

# Spring
spring:

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityRequestMatcherProviderAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

  cache:
    type: JCACHE
    jcache:
      config: classpath:ehcache.xml

  # GSON Configuration
  gson:
    date-format: yyyy-MM-dd

  # Web MVC
  mvc:
    log-resolved-exception: false
    converters:
      preferred-json-mapper: gson

  #DB Schema Initialization
  sql:
    init:
      mode: ALWAYS
      continue-on-error: false
      schema-locations: classpath:/schema.sql


  #Datasource
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/vehicledb}
    username: ${POSTGRES_USER:vehicleuser}
    password: ${POSTGRES_PASSWORD:vehiclepass}

    #Hikari Connection Pool
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 50
      minimum-idle: 10
      connection-test-query: SELECT 1
      auto-commit: false

  #Spring Data JPA
  data:
    jpa:
      repositories:
        enabled: true

  #Java Persistence API
  jpa:
    open-in-view: false
    show-sql: false

    #Hibernate
    hibernate:
      format_sql: false
      ddl-auto: validate
    properties:

      hibernate:
        generate_statistics: false
        #Hibernate Second Level Cache Configuration
        javax.cache.missing_cache_strategy: create
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: jcache

