# Tomcat Server
server:
  port: 8888
  undertow:

    accesslog:
      enabled: false


# Logging
logging:
  level:
    web: INFO

# Spring
spring:
  main:
    lazy-initialization: true

  # Enable Virtual Threads
  threads:
    virtual:
      enabled: true

  #Datasource
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/vehicledb}
    username: ${POSTGRES_USER:vehicleuser}
    password: ${POSTGRES_PASSWORD:vehiclepass}

    #Hikari Connection Pool
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 2000000
      connection-test-query: SELECT 1
      auto-commit: false

  #Spring Data JPA
  data:
    jpa:
      repositories:
        enabled: true

  #Java Persistence API
  jpa:
    open-in-view: true
    show-sql: false

    #Hibernate
    hibernate:
      format_sql: false
      ddl-auto: create-drop